const mostPopularTypes = {
  INIT_MOST_POPULAR: 'INIT_MOST_POPULAR',
  INIT_MOST_POPULAR_ERROR: 'INIT_MOST_POPULAR_ERROR',
  INIT_MOST_POPULAR_SUCCESS: 'INIT_MOST_POPULAR_SUCCESS',
};

export default mostPopularTypes;
